[package]
name = "goldychess_rust"
version = "0.1.0"
authors = ["Michael Goldstein <michael@mgold.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

[profile.release]
opt-level = 3